Add ethereum rust wrapper and provider plugin
polywrap/integrations pull request #124
Opened 2022-10-05 03:30 UTC by fetsorn

2022-10-10 07:14 UTC, krisbitney requested changes
This is amazing! I'm so happy to see how much progress you've made. 

While the wrapper builds with `polywrap build`, it fails `cargo check`. Do you know why?

2022-10-10 07:14 UTC, krisbitney commented on protocol/ethereum/provider/src/index.ts
> +  wallet?: Wallet
Does this mean users need to have ethers as a dependency so they can provider a `Wallet` to the config?

2022-10-28 12:53 UTC, cbrzn commented
hey @fetsorn any updates on this? would love to use this wrapper in the python client :-D

2022-11-17 07:29 UTC, krisbitney commented on protocol/ethereum/provider/src/index.ts
> +      return "";
This branch returns an empty string

2022-11-17 07:30 UTC, krisbitney commented on protocol/ethereum/provider/src/index.ts
> +      return "";
this branch returns an empty string

2022-11-21 16:20 UTC, krisbitney approved these changes

2022-11-21 16:21 UTC, merged