NEAR Plugin and Wrapper
polywrap/integrations pull request #46
Opened 2022-06-08 17:50 UTC by ramilexe

2022-06-14 22:08 UTC, krisbitney requested changes
It's so exciting to see this coming to fruition. I'm happy to see the test coverage has improved significantly since the original Near demo! 

I don't know the scope of your grant, so please take that into consideration when reading my questions.

2022-06-15 08:43 UTC, Brioline commented on protocol/near/plugin-js/schema.graphql
>    sendTransaction(
resolved by https://github.com/polywrap/integrations/pull/46/commits/e3b327a3f4a41332814ee6c833b0394bb0a43291

2022-06-15 08:43 UTC, ramilexe commented on protocol/near/plugin-js/schema.graphql
>    sendTransaction(
We didn't include migrating Borsch (which is required for serialization) to Wrapper in this scope, so we used it through Plugin. We have plan to apply to next grant to improve this and remove Near JS SDK as much as possible.

2022-06-15 08:44 UTC, Brioline commented on protocol/near/wrapper/src/utils/actionCreators.ts
> +import * as bs64 from "as-base64";
resolved by https://github.com/polywrap/integrations/pull/46/commits/e3b327a3f4a41332814ee6c833b0394bb0a43291

2022-06-15 11:20 UTC, krisbitney commented on protocol/near/plugin-js/schema.graphql
>    sendTransaction(
Okay, I see. Cool stuff!

2022-06-15 11:21 UTC, krisbitney approved these changes

2022-06-15 15:43 UTC, dOrgJelli approved these changes
All LGTM! Amazing work 👏

2022-06-15 15:44 UTC, merged