Update ens wrapper to single module and renaming changes
polywrap/integrations pull request #77
Opened 2022-07-05 11:06 UTC by nerfZael

Recipes are not upgraded. I'll create an issue to migrate them to workflows

2022-07-05 11:22 UTC, cbrzn commented on protocol/ethereum/ens/wrapper/package.json
> +    "deploy:polywrap": "npx polywrap build --ipfs http://localhost:5001 --test-ens ens.eth",
Let's update this and use the deploy manifest - You can check it out here

2022-07-05 11:22 UTC, cbrzn commented on protocol/ethereum/ens/wrapper/package.json
> +    "test:recipe": "npx polywrap query ./recipes/e2e.json"
Let's remove this for now

2022-07-05 11:22 UTC, cbrzn commented on protocol/ethereum/ens/wrapper/polywrap.build.yaml
>      - src/common
I think we should not keep the folder common and move everything to one place

2022-07-05 12:01 UTC, Niraj-Kamdar requested changes
LGTM, just wrapper needs rename IMO.

2022-07-05 12:04 UTC, cbrzn commented on protocol/ethereum/ens/wrapper/package.json
> +  "name": "@polywrap/ens-api",
uuu nice catch

2022-07-05 12:05 UTC, cbrzn approved these changes
Once Niraj comment has been addressed this is good to go :green_apple:

2022-07-06 11:29 UTC, Niraj-Kamdar approved these changes
LGTM!

2022-07-06 11:30 UTC, merged