Tezos Wrappers Updated
polywrap/integrations pull request #82
Opened 2022-07-13 17:11 UTC by namesty

2022-07-21 17:28 UTC, Niraj-Kamdar requested changes
update deploy manifests to origin

2022-07-21 17:28 UTC, Niraj-Kamdar commented on protocol/tezos/harbinger-wrapper/src/__tests__/e2e/get-asset-data.spec.ts
> +import { AssetCandle, Providers } from "../../wrap"
Use app codegen instead

2022-07-21 17:28 UTC, Niraj-Kamdar commented on protocol/tezos/harbinger-wrapper/src/__tests__/e2e/get-asset-data.spec.ts
> +      const response =  await client.query<{ getAssetData: AssetCandle}>({
don't use `client.query` anymore. I'd suggest to use app codegen whenever possible and if not then invoke.

2022-07-21 17:28 UTC, Niraj-Kamdar commented on protocol/tezos/harbinger-wrapper/.gitignore
> +.polywrap
add wrap in gitignore

2022-07-21 17:28 UTC, Niraj-Kamdar commented on protocol/tezos/harbinger-wrapper/package.json
> +    "build:polywrap": "npx polywrap build",
Why have separate build:polywrap ?

2022-07-21 17:28 UTC, Niraj-Kamdar commented on README.md
> +| [Tezos Domains Wrapper](./protocol/tezos/tezos-domains-wrapper)     | Complete | w3://ipfs/QmfXgYfxG7Uw7RCGLsAYFCuPcr7xqRePhTgMJVCdGiRMcZ    |
rename w3 -> wrap

2022-07-22 05:48 UTC, namesty commented
> update deploy manifests to origin

Yep, done

2022-07-22 11:49 UTC, Niraj-Kamdar approved these changes

2022-07-22 11:50 UTC, merged